using DataAccess.Attributes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace DataAccess.Extensions
{
    public static class ModelBuilderExtensions
    {
        public static void ApplyAutoGeneratedProperties(this ModelBuilder modelBuilder)
        {
            var dbContextType = modelBuilder.GetType()
                .GetProperty("Model")!
                .DeclaringType!
                .Assembly
                .GetTypes()
                .FirstOrDefault(t => typeof(DbContext).IsAssignableFrom(t));

            if (dbContextType == null)
                throw new InvalidOperationException("No DbContext found in assembly.");

            var dbSets = dbContextType.GetProperties()
                .Where(p => p.PropertyType.IsGenericType &&
                            p.PropertyType.GetGenericTypeDefinition() == typeof(DbSet<>));

            foreach (var dbSetProp in dbSets)
            {
                var entityType = dbSetProp.PropertyType.GetGenericArguments()[0];

                var entityBuilder = modelBuilder.Entity(entityType);

                foreach (var prop in entityType.GetProperties())
                {
                    var attr = prop.GetCustomAttribute<AutoGeneratedAttribute>();
                    if (attr == null) continue;

                    ApplyFluentConfiguration(entityBuilder, prop, attr);
                }
            }
        }

        private static void ApplyFluentConfiguration(
            EntityTypeBuilder entityBuilder,
            PropertyInfo prop,
            AutoGeneratedAttribute attr)
        {
            var propertyBuilder = entityBuilder.Property(prop.PropertyType, prop.Name);

            if (!typeof(ValueGenerator).IsAssignableFrom(attr.ValueGeneratorType))
            {
                throw new InvalidOperationException(
                    $"El tipo '{attr.ValueGeneratorType.Name}' no es un ValueGenerator valido");
            }
            propertyBuilder.HasValueGenerator(attr.ValueGeneratorType);

                switch (attr.ValueGenerated)
                {
                    case ValueGenerated.Never:
                        propertyBuilder.ValueGeneratedNever();
                        break;
                    case ValueGenerated.OnAdd:
                        propertyBuilder.ValueGeneratedOnAdd();
                        break;
                    case ValueGenerated.OnUpdate:
                        propertyBuilder.ValueGeneratedOnUpdate();
                        break;
                    case ValueGenerated.OnUpdateSometimes:
                        propertyBuilder.ValueGeneratedOnUpdateSometimes();
                        break;
                    case ValueGenerated.OnAddOrUpdate:
                        propertyBuilder.ValueGeneratedOnAddOrUpdate();
                        break;
                    default:
                        break;
                }

            if (attr.OnCreateBehavior != null)
                propertyBuilder.Metadata.SetAfterSaveBehavior(attr.OnCreateBehavior);

            if (attr.OnUpdateBehavior != null)
                propertyBuilder.Metadata.SetAfterSaveBehavior(attr.OnUpdateBehavior);

        }
    }
}
