using DataAccess.Attributes;
using DataAccess.ValueGenerators;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.Entities.Base
{
    public interface IAuditable
    {

        //[AutoGenerated(typeof(UserSignValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        //public string? CreatedBy { get; set; }

        //[AutoGenerated(typeof(DateTimeValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        //public DateTime CreatedAt { get; set; }

        //[AutoGenerated(typeof(UserSignValueGenerator), ValueGenerated.OnUpdate, OnCreateBehavior = PropertySaveBehavior.Ignore)]
        //public string? UpdatedBy { get; set; }

        //[AutoGenerated(typeof(DateTimeValueGenerator), ValueGenerated.OnUpdate, OnCreateBehavior = PropertySaveBehavior.Ignore)]
        //public DateTime UpdatedAt { get; set; }

        [AutoGenerated(typeof(UserSignValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        public string? UserId { get; set; }

        [AutoGenerated(typeof(DateTimeValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        public DateTime Created { get; set; }
    }
}
