using DataAccess.Attributes;
using DataAccess.ValueGenerators;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.Entities.Base
{
    public interface ICompanyIdentity
    {
        [AutoGenerated(typeof(CompaniaSignValueGenerator), ValueGenerated.OnAdd)]
        public string? CompaniaId { get; set; }
    }
}
