using DataAccess.Attributes;
using DataAccess.ValueGenerators;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataAccess.Entities.Base
{
    public interface IDireccionIdentity
    {

        [AutoGenerated(typeof(DireccionInstitucionalSignValueGenerator), ValueGenerated.OnAdd)]
        public string? DireccionInstitucionalId { get; set; }
    }
}
