using DataAccess.Attributes;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.ValueGeneration;

namespace DataAccess.Entities.Base
{
    public interface IIdentity
    {
        [AutoGenerated(typeof(GuidValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        public string? Id { get; set; }

    }
}
