
using DataAccess.Attributes;
using DataAccess.ValueGenerators;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.Entities.Base
{
    public interface ISucursalIdentity
    {

        [AutoGenerated(typeof(SucursalSignValueGenerator), ValueGenerated.OnAdd)]
        public string? SucursalId { get; set; }
    }
}
