using DataAccess.Attributes;
using DataAccess.ValueGenerators;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.Entities.Base
{
    public interface IUserIdentity
    {
        [AutoGenerated(typeof(UserSignValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        public string? UserId { get; set; }
        //public string? Id { get; set; }
    }

}
