using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.Attributes
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class AutoGeneratedAttribute : Attribute
    {
        public Type ValueGeneratorType { get; set; }
        public ValueGenerated ValueGenerated { get; set; }
        public PropertySaveBehavior OnUpdateBehavior { get; set; }
        public PropertySaveBehavior OnCreateBehavior { get; set; }

        public AutoGeneratedAttribute(Type valueGeneratorType, 
            ValueGenerated valueGeneratedOn, 
            PropertySaveBehavior afterSaveBehavior = PropertySaveBehavior.Save,
            PropertySaveBehavior beforeSaveBehavior = PropertySaveBehavior.Save)
        {
            this.ValueGeneratorType = valueGeneratorType;
            this.ValueGenerated = valueGeneratedOn;
            this.OnUpdateBehavior = afterSaveBehavior;
            this.OnCreateBehavior = beforeSaveBehavior;
        }

    }
}
