using DataAccess.Attributes;
using DataAccess.Entities.Base;
using DataAccess.ValueGenerators;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess.Entities
{
    public class Requisicion : IIdentity, ICompanyIdentity, IDireccionIdentity, ISucursalIdentity
    {
        public string? Id { get; set; }
        public string? CompaniaId { get; set; }
        public int? ObjectType { get; }
        public string? DireccionInstitucionalId { get; set; }
        public DateTime? Fecha { get; set; }
        public DateTime? FechaRequerida { get; set; }
        public string? SucursalId { get; set; }
        public string? DepartamentoId { get; set; }
        public string? AreaId { get; set; }

        [AutoGenerated(typeof(UserSignValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        public string? UserId { get; set; }

        [AutoGenerated(typeof(DateTimeValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        public DateTime Created { get; set; }

        public List<DetalleRequisicion> Detalles { get; set; } = new List<DetalleRequisicion>();

    }
}
