
using DataAccess.Attributes;
using DataAccess.Entities.Base;
using DataAccess.ValueGenerators;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DataAccess
{
    public class BaseSystemData : IIdentity, ICompanyIdentity
    {
        public string? Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public virtual int ObjectType { get; set; }
        public bool Active { get; set; }
        public long LogInstance { get; set; }

        [AutoGenerated(typeof(DateTimeValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        public DateTime? CreatedAt { get; set; }

        [AutoGenerated(typeof(DateTimeValueGenerator), ValueGenerated.OnUpdate, OnCreateBehavior = PropertySaveBehavior.Ignore)]
        public DateTime? UpdatedAt { get; set; }

        [AutoGenerated(typeof(UserSignValueGenerator), ValueGenerated.OnAdd, OnUpdateBehavior = PropertySaveBehavior.Ignore)]
        public string? CreatedBy { get; set; }

        [AutoGenerated(typeof(UserSignValueGenerator), ValueGenerated.OnUpdate, OnCreateBehavior = PropertySaveBehavior.Ignore)]
        public string? UpdatedBy { get; set; }
        public string? CompaniaId { get; set; }
    }
}
